import type { Candidate, InterestProfile, Preferences } from '../types.js';
import type { Provider } from './types.js';

const items: Candidate[] = [
  {
    id: 'learn_recsys_stanford',
    title: "Study Stanford CS246 — Mining Massive Datasets (Recommender Systems lecture)",
    description: 'Free lecture notes covering collaborative filtering, matrix factorization, and ranking — directly relevant to building recommendation engines.',
    url: 'http://web.stanford.edu/class/cs246/',
    category: 'learning',
    tags: ['ai', 'programming'],
    difficulty: 'intermediate',
    estimatedMinutes: 90,
    popularity: 0.65,
    addedAt: Date.parse('2025-01-10'),
    suitedWindows: ['tomorrow', 'weekend'],
  },
  {
    id: 'learn_mit_ocw_quantum',
    title: 'Watch MIT OCW 8.370x — Quantum Information Science I',
    description: 'Lecture 1 covers qubits and superposition from first principles — matches a structured quantum self-study roadmap.',
    url: 'https://ocw.mit.edu/',
    category: 'learning',
    tags: ['quantum_computing'],
    difficulty: 'intermediate',
    estimatedMinutes: 75,
    popularity: 0.58,
    addedAt: Date.parse('2025-02-15'),
    suitedWindows: ['tomorrow', 'weekend'],
  },
  {
    id: 'learn_vector_databases',
    title: 'Learn Vector Databases (embeddings, ANN search, pgvector/FAISS)',
    description: 'Short practical primer on how embeddings are stored and queried — foundational for any RAG or recommendation project.',
    category: 'learning',
    tags: ['ai', 'programming'],
    difficulty: 'intermediate',
    estimatedMinutes: 50,
    popularity: 0.7,
    addedAt: Date.parse('2025-06-01'),
    suitedWindows: ['tomorrow'],
  },
  {
    id: 'learn_system_design_primer',
    title: "Study 'system-design-primer' fundamentals",
    description: 'Load balancing, caching, and database scaling patterns — asked in nearly every SWE interview loop.',
    category: 'learning',
    tags: ['career', 'programming'],
    difficulty: 'intermediate',
    estimatedMinutes: 60,
    popularity: 0.8,
    addedAt: Date.parse('2024-10-01'),
    suitedWindows: ['tomorrow', 'weekend'],
  },
  {
    id: 'learn_typescript_deep_dive',
    title: 'Work through TypeScript generics & utility types',
    description: 'Mapped types, conditional types, and generics — the exact features used throughout this codebase.',
    category: 'learning',
    tags: ['programming', 'web_dev'],
    difficulty: 'intermediate',
    estimatedMinutes: 40,
    popularity: 0.62,
    addedAt: Date.parse('2025-03-20'),
    suitedWindows: ['now', 'tomorrow'],
  },
  {
    id: 'learn_discrete_math_relations',
    title: 'Revise equivalence relations & tautology proofs',
    description: 'Refresher exercises on reflexive/symmetric/transitive relations and truth-table proofs — solid prep for a discrete math internal.',
    category: 'learning',
    tags: ['programming'],
    difficulty: 'beginner',
    estimatedMinutes: 45,
    popularity: 0.4,
    addedAt: Date.parse('2025-07-01'),
    suitedWindows: ['now', 'tomorrow'],
  },
];

export const learningProvider: Provider = {
  category: 'learning',
  name: 'Learning Provider',
  getCandidates: (_prefs: Preferences, _profile: InterestProfile): Promise<Candidate[]> =>
    Promise.resolve(items),
};
